### ISSUE TITLE
How do you test this?

### ISSUE THREAD

**Issue by KeizerDev** [TeamNewPipe/PipeCast#1]
Do you have any thing like tests how you check if it actually works? I need something like that to be able to contribute.

**Comment by KeizerDev** [comment]
Oh, you told me it in TeamNewPipe/NewPipe#668. To help others, add something like this. (BTW, we need to create tests)

```
import java.io.IOException;
import java.util.List;
import java.util.concurrent.ExecutionException;

import org.schabi.newpipe.cast.CastingProtocol;
import org.schabi.newpipe.cast.Device;
import org.schabi.newpipe.cast.Discoverer;
import org.schabi.newpipe.cast.PipeCast;
import org.schabi.newpipe.cast.exceptions.ProtocolNotFoundException;

public class App {
    public static void main(String[] args) throws ProtocolNotFoundException, IOException, InterruptedException, ExecutionException {
        CastingProtocol castingProtocol = PipeCast.getProtocol("UPnP");
        Discoverer discoverer = castingProtocol.getDiscoverer();
        List<Device> devices = discoverer.discoverDevices();
        for (Device device : devices) {
            System.out.println(device.getName());
        }
        System.exit(0);
    }
}
```

**Comment by ghost** [comment]
Well, I first want it to be able to actually cast (it only supports
discovery atm), before I'll write tests. But the tests would be hard to
test, since those devices woud need to exist on your network.

**Comment by theScrabi** [comment]
Could it be mocked?

**Comment by ghost** [comment]
@theScrabi: Yes, but then there isn't really a point of testing it anymore.
So I think manually testing is the only thing that'd really work.

**Comment by theScrabi** [comment]
Hm i see.

**Comment by ghost** [comment]
The best way for manually testing this would be:

1. Download Gradle (preferably the same version as defined [here](https://github.com/TeamNewPipe/PipeCast/blob/master/gradle/wrapper/gradle-wrapper.properties))
2. Create a new folder
3. Run `/path/to/gradle/bin/gradle init --type java-application`
4. Clone this repo in it
5. Add `include ':PipeCast'` to `settings.gradle`
6. Add `implementation project(':PipeCast')` to the `dependencies` in `build.gradle`
7. Remove the other `dependencies` in `build.gradle`
8. Remove `src/tests`
9. Import the whole thing into your IDE
10. Call the PipeCast stuff from `App.java`
11. If you're testing UPnP A/V, run [GMediaRender Resurrect](https://github.com/hzeller/gmrender-resurrect) on another PC
12. Run the stuff from your IDE
